url: https://seanpackham.com
version: 5

permalink: pretty

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - README.md

collections:
  projects:
    output: true

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      type: "projects"
    values:
      layout: "project"
